### ISSUE TITLE
Describe the hardware

### ISSUE THREAD

**Issue by lieberk2-hd** [MuellerDominik/BMS-Software#1]
Can you describe the hardware that this communicates with?
Is it a demo board or something?

**Comment by MuellerDominik** [comment]
It's a custom prototype board. You'll find all the relevant information here: [theBMS](https://github.com/MuellerDominik/theBMS)

**Comment by lieberk2-hd** [comment]
Thanks.  Very interesting!  Did you ever get this up and running for real?
